### ISSUE TITLE
🐛 Bug Report: 

### ISSUE THREAD

**Issue by tequilaonelove** [appwrite/sdk-for-kotlin#14] opened 2021-11-17 18:32 UTC
### 👟 Reproduction steps

    launch(Dispatchers.IO) {
        try {
            val client = Client()
                .setEndpoint("http://127.0.0.1/v1")
                .setProject("619505812e4d0")
                .setKey("94c9dad4e9041994a7470289b01c69......d87bd7d4d27a5ea30c804cae865")
                .setSelfSigned(true)

            val database = io.appwrite.services.Database(client)

            for (i in 0..10000) {
                val response = database.createDocument(
                    collectionId = "6195069ccabcf",
                    data = mapOf(
                        "userId" to "user${i}@gmail.com",
                        "premiumStatus" to true,
                        "expiredTo" to 123456
                    ),
                )
                val json = response.isSuccessful
                log.info("res $i is $json")
                delay(10)
            }

        } catch (e: Exception) {
            log.error("Exception: ", e)
        } catch (er: AppwriteException) {
            log.error("AppwriteException: ", er)
        }
    }

### 👍 Expected behavior

All this was done for the sake of verification.
It was expected that all documents (data) will be successfully created or the server will not hang from this.

### 👎 Actual Behavior

The service is now unavailable and does not restart.
Restarting Docker, containers gave no results.

### 🎲 Appwrite version

Version 0.10.x

### 💻 Operating system

Windows

### 🧱 Your Environment

I use WSL2

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by eldadfux** [comment] 2021-11-17 22:12
Hey @tequilaonelove what do you see in your Appwrite logs?

**Comment by stnguyen90** [comment] 2021-11-18 01:34
@tequilaonelove, would you please update the issue title to include a descriptive summary? 

Also, are you suggesting the problem is with the Kotlin SDK? I suspect your appwrite instance might be locking up because it isn't able to handle the load (Docker containers don't perform as well in WSL).

Btw, I ran the equivalent in Python and it finished fine:

```python
import logging
import time

from appwrite.client import Client
from appwrite.services.database import Database

logging.basicConfig(level=logging.DEBUG)

try:
    # Initialise the Appwrite client
    client = Client()
    client.set_endpoint('https://my_domain/v1') # Your API Endpoint
    client.set_project('my_project') # Your project ID
    client.set_key('my_key') # Your secret API key

    # Initialize the database SDK with the client object
    database = Database(client)

    # Perform your task
    for i in range(0, 10000):
        result = database.create_document(
            "collection_id", 
            {
                "number": i
            },
            ["*"],
            ["*"]
        )
        logging.info("res %d is %s", i, result)
        time.sleep(10/1000)
except Exception as err:
    logging.exception(err)

```

**Comment by tequilaonelove** [comment] 2021-11-23 19:21
Im dont close connections in code: response.body?.close().

**Comment by stnguyen90** [comment] 2021-11-23 22:25
> Im dont close connections in code: response.body?.close().

@tequilaonelove, are you asking if you need to call close? I don't think you need to.

Also, again, would you please update the issue title to be more descriptive? And perhaps you can provide the appwrite logs?

**Comment by lohanidamodar** [comment] 2022-02-11 05:51
Closing this issue, as there's been no new update and it lacks proper information to help resolve the issue. Feel free to reopen with more information if the issue still exist.

**Closed by lohanidamodar** 2022-02-11 05:51 UTC
Labels: bug
